#!/usr/bin/env node
/**
 * setup-hooks.js — CostoBot
 * Installs (or uninstalls) the post-commit versioning hook.
 *
 * Usage:
 *   node frontend/setup-hooks.js          → Install hook
 *   node frontend/setup-hooks.js --remove → Remove hook
 *
 * Run this after every fresh `git clone`.
 * [GREENFIELD — defined by user]
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const REMOVE = process.argv.includes('--remove');

// Find .git directory (walk up from workspace root)
function findGitDir(startDir) {
  let dir = startDir;
  for (let i = 0; i < 5; i++) {
    const candidate = path.join(dir, '.git');
    if (fs.existsSync(candidate)) return candidate;
    dir = path.dirname(dir);
  }
  return null;
}

const workspaceRoot = path.join(__dirname, '..');
const gitDir = findGitDir(workspaceRoot);

if (!gitDir) {
  console.error('❌ .git directory not found. Run this from inside the git repository.');
  process.exit(1);
}

const hooksDir = path.join(gitDir, 'hooks');
const hookPath = path.join(hooksDir, 'post-commit');
const postCommitScript = path.join(__dirname, 'post-commit-version.js');

if (REMOVE) {
  if (fs.existsSync(hookPath)) {
    fs.unlinkSync(hookPath);
    console.log('✅ Post-commit hook removed.');
  } else {
    console.log('ℹ️  No hook installed — nothing to remove.');
  }
  process.exit(0);
}

// --- Install hook ---
if (!fs.existsSync(hooksDir)) {
  fs.mkdirSync(hooksDir, { recursive: true });
}

const hookContent = `#!/bin/sh
# CostoBot AUTONOMOUS versioning hook
# Auto-generated by setup-hooks.js — do not edit manually
# To remove: node frontend/setup-hooks.js --remove

node "${postCommitScript.replace(/\\/g, '/')}"
`;

fs.writeFileSync(hookPath, hookContent, { mode: 0o755 });

// Make executable (Unix/Git Bash)
try {
  execSync(`chmod +x "${hookPath}"`);
} catch {
  // Windows without Git Bash — file permissions set via mode flag above
}

console.log('✅ Post-commit hook installed at:', hookPath);
console.log('');
console.log('🎯 How it works:');
console.log('   git commit -m "🐛 fix: bug title"   → auto PATCH bump');
console.log('   git commit -m "✨ feat: new feature" → auto MINOR bump');
console.log('   git commit -m "💥 BREAKING change"   → auto MAJOR bump');
console.log('   Any other prefix                     → skipped (no version bump)');
console.log('');
console.log('💡 To bypass: git commit --no-verify -m "your message"');
console.log('💡 To remove: node frontend/setup-hooks.js --remove');
